#!/usr/bin/env php
<?php
require dirname(__FILE__) . '/config/config.php';

define('JSBIN_SPROCKETIZED', './js/tmp.' . JSBIN_VERSION . '.js');
define('JSBIN_PRODUCTION', './js/jsbin-' . JSBIN_VERSION . '.js');

// sprocketize the code in to _jsbin.JSBIN_VERSION.js
require_once('lib/sprockets/sprocket.php');

echo "Sprocketizing...\n";

$filePath = './js/jsbin.js';
// prepare sprocket
$sprocket = new Sprocket($filePath, array(    
	'contentType' => '', // keeps debug quiet
	'baseUri' => '../js',
  'baseFolder' => array('./js/vendor', './js/vendor/codemirror'),
  'assetFolder' => '..',
	'debugMode' => true, // forces to always show
  'autoRender' => false
));

// having to hack the source path to get it work properly.
// $sprocket->filePath = '.' . $sprocket->filePath);

// concat complete
echo "Rendering...\n";
$js = $sprocket->render(true);

// write concat to js dir
echo "Writing concatenated file...\n";
file_put_contents(JSBIN_SPROCKETIZED, $js);

// google compile in to jsbin.JSBIN_VERSION.js
echo "Google compiler compressing...\n";
system('java -jar "./lib/compiler.jar" --js="' . JSBIN_SPROCKETIZED . '" --js_output_file="' . JSBIN_PRODUCTION . '" --warning_level=QUIET');

unlink(JSBIN_SPROCKETIZED);
echo "Compressed: " . JSBIN_PRODUCTION . "\nFile size: " . filesize(JSBIN_PRODUCTION) . " bytes.\n";
?>
